# Configurações da aplicação
spring:
  application:
    name: bolt-energy-app
  
  # Configuração do banco de dados MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/bolt_energy_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
      javax.persistence.schema-generation.database.action: update
  
# Configuração do servidor
server:
  port: 8182

# Configuração de logging
logging:
  level:
    root: INFO
    com.boltenergy: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuração do SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tags-sorter: alpha
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  server:
    port: 8182  # Mesma porta da aplicação

# Configurações do WebClient
webclient:
  max-in-memory-size: 50MB
  connect-timeout: 300s  # 5 minutos para conexão
  response-timeout: 300s  # 5 minutos para resposta
  read-timeout: 600s     # 10 minutos para leitura total
  buffer-size: 1MB

# Configurações de banco de dados (exemplo com H2 em memória)
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

# Configuração de agendamento do serviço RALIE
ralie:
  schedule:
    # Expressão cron para executar a cada minuto (no segundo 0 de cada minuto)
    # Para executar a cada hora, use: 0 0 * * * *
    # Para executar a cada 30 minutos: 0 */30 * * * *
    # Para executar a cada 5 minutos: 0 */5 * * * *
    cron: 0 0 * * * *  # Executa a cada hora
    # cron: 0 * * * * *  # Executa a cada minuto
    enabled: true
    # Nome do job para logs
    job-name: "RALIE Download Job"
